# Generated by Django 5.2a1 on 2025-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('tipas', models.CharField(choices=[('Adventui', 'Adventui'), ('Rasoms', 'Rasoms'), ('Lygiadieniui', 'Lygiadieniui'), ('Vakaronei', 'Vakaronei'), ('Kaledoms', 'Kalėdoms'), ('Velykoms', 'Velykoms'), ('Susidainavimams', 'Susidainavimams')], max_length=50)),
                ('aprasymas', models.TextField(blank=True, null=True)),
                ('sukurtas', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
