# Generated by Django 5.2a1 on 2025-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0001_initial'),
        ('Programos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='kuriniai',
            field=models.ManyToManyField(related_name='programos', to='Kuriniai.kurinys'),
        ),
    ]
