# Generated by Django 5.2a1 on 2025-02-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0001_initial'),
        ('Programos', '0002_programa_kuriniai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='kuriniai',
        ),
        migrations.CreateModel(
            name='ProgramaKurinys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eile', models.PositiveIntegerField(default=1)),
                ('kurinys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kuriniai.kurinys')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programos.programa')),
            ],
            options={
                'ordering': ['eile'],
                'unique_together': {('programa', 'kurinys')},
            },
        ),
    ]
