# Generated by Django 5.2a1 on 2025-02-19 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0001_initial'),
        ('Programos', '0003_remove_programa_kuriniai_programakurinys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramosKurinys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eile', models.PositiveIntegerField()),
                ('kurinys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kuriniai.kurinys')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programos.programa')),
            ],
            options={
                'ordering': ['eile'],
            },
        ),
        migrations.DeleteModel(
            name='ProgramaKurinys',
        ),
    ]
