# Generated by Django 5.0.12 on 2025-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0004_programoskurinys_delete_programakurinys'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='trukme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
