# Generated by Django 5.0.12 on 2025-03-18 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0005_programa_trukme'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
