# Generated by Django 5.0.12 on 2025-03-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0006_programa_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='created_at',
        ),
    ]
