# Generated by Django 5.0.12 on 2025-03-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Programos', '0007_remove_programa_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='ansamblis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ansambliai.ansamblis'),
        ),
    ]
