# Generated by Django 5.0.12 on 2025-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0008_programa_ansamblis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='trukme',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
