# Generated by Django 5.0.12 on 2025-04-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0009_alter_programa_trukme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='trukme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
