# Generated by Django 5.0.12 on 2025-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansamblis',
            name='sudetingumas',
            field=models.CharField(blank=True, choices=[('Vaikų', 'Vaikų'), ('Jaunimo', 'Jaunimo'), ('Suaugusių', 'Suaugusių')], max_length=20, null=True),
        ),
    ]
