# Generated by Django 5.0.12 on 2025-04-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0002_ansamblis_sudetingumas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansamblis',
            name='sudetingumas',
        ),
    ]
