# Generated by Django 5.0.12 on 2025-04-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0003_remove_ansamblis_sudetingumas'),
        ('Padaliniai', '0006_remove_padalinys_ansambliai'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansamblis',
            name='padalinys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ansambliai', to='Padaliniai.padalinys'),
        ),
    ]
