# Generated by Django 5.0.12 on 2025-04-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ensembles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Daina', 'Daina'), ('Šokis', 'Šokis'), ('Kapela', 'Kapela'), ('Instrumentalas', 'Instrumentalas')], max_length=20)),
                ('speed', models.CharField(blank=True, choices=[('Lėtas', 'Lėtas'), ('Vidutinis', 'Vidutinis'), ('Greitas', 'Greitas')], max_length=20, null=True)),
                ('preparation', models.CharField(choices=[('Naujas', 'Naujas'), ('Ruošiamas', 'Ruošiamas'), ('Paruoštas', 'Paruoštas'), ('Archyvas', 'Archyvas')], default='Naujas', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='natos/')),
                ('notes_image', models.ImageField(blank=True, null=True, upload_to='natos_images/')),
                ('region', models.CharField(blank=True, choices=[('Aukštaitija', 'Aukštaitija'), ('Žemaitija', 'Žemaitija'), ('Dzūkija', 'Dzūkija'), ('Suvalkija', 'Suvalkija'), ('Mažoji Lietuva', 'Mažoji Lietuva')], max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ensembles', models.ManyToManyField(to='Ensembles.ensemble')),
                ('features', models.ManyToManyField(blank=True, to='Pieces.feature')),
            ],
        ),
    ]
