# Generated by Django 5.2a1 on 2025-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurinys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('tipas', models.CharField(choices=[('Daina', 'Daina'), ('Šokis', 'Šokis'), ('Kapela', 'Kapela')], max_length=20)),
                ('trukme', models.CharField(max_length=10)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
