# Generated by Django 5.2a1 on 2025-02-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurinys',
            name='trukme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
