# Generated by Django 5.0.12 on 2025-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0002_alter_kurinys_trukme'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
