# Generated by Django 5.0.12 on 2025-03-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Kuriniai', '0003_kurinys_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='ansamblis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuriniai', to='Ansambliai.ansamblis'),
        ),
        migrations.AddField(
            model_name='kurinys',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
