# Generated by Django 5.0.12 on 2025-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Kuriniai', '0004_kurinys_ansamblis_kurinys_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurinys',
            name='ansamblis',
        ),
        migrations.AddField(
            model_name='kurinys',
            name='ansambliai',
            field=models.ManyToManyField(blank=True, to='Ansambliai.ansamblis'),
        ),
    ]
