# Generated by Django 5.0.12 on 2025-03-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Kuriniai', '0005_remove_kurinys_ansamblis_kurinys_ansambliai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurinys',
            name='ansambliai',
            field=models.ManyToManyField(to='Ansambliai.ansamblis'),
        ),
        migrations.AlterField(
            model_name='kurinys',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 17, 12, 57, 57, 786850, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
