# Generated by Django 5.0.12 on 2025-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0006_alter_kurinys_ansambliai_alter_kurinys_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='regionas',
            field=models.CharField(blank=True, choices=[('Aukštaitija', 'Aukštaitija'), ('Žemaitija', 'Žemaitija'), ('Mažoji Lietuva', 'Mažoji Lietuva'), ('Suvalkija', 'Suvalkija'), ('Dzūkija', 'Dzūkija')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kurinys',
            name='vieta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
