# Generated by Django 5.0.12 on 2025-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0007_kurinys_regionas_kurinys_vieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='aprašymas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kurinys',
            name='regionas',
            field=models.CharField(blank=True, choices=[('aukštaitija', 'Aukštaitija'), ('žemaitija', 'Žemaitija'), ('dzūkija', 'Dzūkija'), ('suvalkija', 'Suvalkija'), ('mažoji', 'Mažoji Lietuva')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kurinys',
            name='vieta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
