# Generated by Django 5.0.12 on 2025-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0008_kurinys_aprašymas_alter_kurinys_regionas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurinys',
            name='regionas',
            field=models.CharField(blank=True, choices=[('Aukštaitija', 'Aukštaitija'), ('Žemaitija', 'Žemaitija'), ('Dzūkija', 'Dzūkija'), ('Suvalkija', 'Suvalkija'), ('Mažoji Lietuva', 'Mažoji Lietuva')], max_length=20, null=True),
        ),
    ]
