# Generated by Django 5.0.12 on 2025-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0009_alter_kurinys_regionas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='natos',
            field=models.FileField(blank=True, null=True, upload_to='natos/'),
        ),
    ]
