# Generated by Django 5.0.12 on 2025-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0010_kurinys_natos'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='natos_image',
            field=models.ImageField(blank=True, null=True, upload_to='natos_images/'),
        ),
    ]
