# Generated by Django 5.0.12 on 2025-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0011_kurinys_natos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozymis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kurinys',
            name='sudetingumas',
            field=models.CharField(blank=True, choices=[('Lengvas', 'Lengvas'), ('Vidutinis', 'Vidutinis'), ('Sunkus', 'Sunkus')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kurinys',
            name='pozymiai',
            field=models.ManyToManyField(blank=True, to='Kuriniai.pozymis'),
        ),
    ]
