# Generated by Django 5.0.12 on 2025-03-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0012_pozymis_kurinys_sudetingumas_kurinys_pozymiai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurinys',
            old_name='aprašymas',
            new_name='aprasymas',
        ),
    ]
