# Generated by Django 5.0.12 on 2025-04-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0013_rename_aprašymas_kurinys_aprasymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurinys',
            name='paruosimas',
            field=models.CharField(blank=True, choices=[('Lengvas', 'Lengvas'), ('Vidutinis', 'Vidutinis'), ('Sunkus', 'Sunkus')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kurinys',
            name='tipas',
            field=models.CharField(choices=[('Daina', 'Daina'), ('Šokis', 'Šokis'), ('Kapela', 'Kapela'), ('Instrumentalas', 'Instrumentalas')], max_length=20),
        ),
    ]
