# Generated by Django 5.0.12 on 2025-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuriniai', '0015_remove_kurinys_sudetingumas_kurinys_greitumas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurinys',
            name='paruosimas',
            field=models.CharField(choices=[('Naujas', 'Naujas'), ('Ruošiamas', 'Ruošiamas'), ('Paruoštas', 'Paruoštas'), ('Archyvas', 'Archyvas')], default='Naujas', max_length=20),
        ),
    ]
