# Generated by Django 5.0.12 on 2025-04-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ensembles', '0001_initial'),
        ('Pieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='Ensembles.ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pieces.piece')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rehearsals.rehearsal')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('rehearsal', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='pieces',
            field=models.ManyToManyField(through='Rehearsals.RehearsalPiece', to='Pieces.piece'),
        ),
    ]
