# Generated by Django 5.0.12 on 2025-04-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensembles', '0002_remove_ensemble_unit_ensemble_department'),
        ('Instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentai', to='Ensembles.ensemble'),
        ),
    ]
