# Generated by Django 5.2a1 on 2025-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renginys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansamblis', models.CharField(max_length=255)),
                ('pavadinimas', models.CharField(max_length=255)),
                ('adresas', models.TextField()),
                ('data_laikas', models.DateTimeField()),
            ],
        ),
    ]
