# Generated by Django 5.2a1 on 2025-02-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Renginiai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renginys',
            name='ansamblis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ansambliai.ansamblis'),
        ),
    ]
