# Generated by Django 5.0.12 on 2025-03-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programos', '0005_programa_trukme'),
        ('Renginiai', '0002_alter_renginys_ansamblis'),
    ]

    operations = [
        migrations.AddField(
            model_name='renginys',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programos.programa'),
        ),
    ]
