# Generated by Django 5.0.12 on 2025-03-18 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renginiai', '0003_renginys_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='renginys',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
