# Generated by Django 5.0.12 on 2025-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kuriniai', '0002_alter_kurinys_trukme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeticija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('kuriniai', models.ManyToManyField(related_name='repeticijos', to='Kuriniai.kurinys')),
            ],
        ),
    ]
