# Generated by Django 5.0.12 on 2025-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repeticijos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeticija',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
