# Generated by Django 5.0.12 on 2025-03-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Repeticijos', '0003_repeticija_ansambliai_repeticija_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeticija',
            name='ansambliai',
        ),
        migrations.AddField(
            model_name='repeticija',
            name='ansambliai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeticijos', to='Ansambliai.ansamblis'),
        ),
    ]
