# Generated by Django 5.0.12 on 2025-03-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repeticijos', '0004_remove_repeticija_ansambliai_repeticija_ansambliai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeticija',
            old_name='ansambliai',
            new_name='ansamblis',
        ),
    ]
