# Generated by Django 5.0.12 on 2025-03-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Repeticijos', '0005_rename_ansambliai_repeticija_ansamblis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeticija',
            name='ansamblis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeticijos', to='Ansambliai.ansamblis'),
        ),
    ]
