# Generated by Django 5.0.12 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Initial', '0002_user_ansambliai'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pavarde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vardas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
