# Generated by Django 5.0.9 on 2025-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padalinys2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.TextField()),
                ('adresas', models.TextField()),
                ('telNr', models.BigIntegerField()),
            ],
        ),
    ]
