# Generated by Django 5.0.9 on 2025-01-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Padaliniai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padalinys2',
            new_name='Padalinys',
        ),
    ]
