# Generated by Django 5.2a1 on 2025-02-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Padaliniai', '0002_rename_padalinys2_padalinys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padalinys',
            name='telNr',
        ),
        migrations.AddField(
            model_name='padalinys',
            name='tel_nr',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='padalinys',
            name='pavadinimas',
            field=models.CharField(max_length=255),
        ),
    ]
