# Generated by Django 5.0.12 on 2025-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansambliai', '0001_initial'),
        ('Padaliniai', '0003_remove_padalinys_telnr_padalinys_tel_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padalinys',
            name='ansambliai',
            field=models.ManyToManyField(related_name='padaliniai', to='Ansambliai.ansamblis'),
        ),
    ]
