# Generated by Django 5.0.12 on 2025-04-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Padaliniai', '0005_alter_padalinys_tel_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padalinys',
            name='ansambliai',
        ),
    ]
