# Generated by Django 5.0.12 on 2025-04-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ensembles', '0001_initial'),
        ('Pieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Adventui', 'Adventui'), ('Rasoms', 'Rasoms'), ('Lygiadieniui', 'Lygiadieniui'), ('Vakaronei', 'Vakaronei'), ('Kaledoms', 'Kalėdoms'), ('Velykoms', 'Velykoms'), ('Susidainavimams', 'Susidainavimams')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ensembles.ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.PositiveIntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pieces.piece')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
            ],
            options={
                'ordering': ['queue'],
            },
        ),
    ]
