# Generated by Django 5.1.2 on 2024-10-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansamblis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('padalinys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansambliai', to='apis.padalinys')),
            ],
        ),
    ]
