# Generated by Django 5.1.2 on 2024-10-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_ansamblis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=255)),
                ('pavarde', models.CharField(max_length=255)),
                ('ansamblis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nariai', to='apis.ansamblis')),
            ],
        ),
    ]
