# Generated by Django 5.1.2 on 2024-10-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_narys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Narys',
            new_name='Nariai',
        ),
    ]
