# Generated by Django 5.1.2 on 2024-10-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_narys_nariai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nariai',
            new_name='Narys',
        ),
    ]
