# Generated by Django 5.2a1 on 2025-02-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ansambliai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('nuotrauka', models.URLField(blank=True, null=True)),
                ('ansamblis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentai', to='Ansambliai.ansamblis')),
            ],
        ),
    ]
