# Generated by Django 5.0.12 on 2025-03-12 15:51

import Instrumentai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentai', '0002_alter_instrumentas_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentas',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to=Instrumentai.models.instrumentas_image_upload_path),
        ),
    ]
